### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by flynnamy** [haha-lisa/Diffstyler#2]
Hi, it missing the networks, danbooru_128, imagenet_128 and yfcc_1 python files,please check it. @haha-lisa

**Comment by sirwalt** [comment]
@flynnamy the referenced models don't seem to be used within the code. You can comment the references and exports within the file. Additionally I found:

+ main.py:line 22 imports networks module, which should be considered in requirements.txt
+ main.py:line 23 imports a custom dependency "net", which causes all subsequent issues (comment for now)
+ main.py:line 206-208 need to be commented for now, because of missing dependcies
+ main.py:line 319-332 need to be commented and substituted by "return 0."

I found with this changes inference is possible and you get results. As the missing part is about the Patchwise Content Loss, the quality suffers as described in their paper.

@haha-lisa thank you for making the code of this model available. I would appreciate if you could make the code for the "AdaInEncoder" available. Further there is the "netF", which you mention as "linear projection" in your paper. If I don't get it wrong the netF contains an MLP with (non-linear) ReLu activations, but the weights seem to be initialized nowhere in the code. Is there something missing as well? Appreciate your support.

**Comment by flynnamy** [comment]
@sirwalt The networks does not include in requirements.txt. It should be a python file or module to define network of model.

**Comment by sirwalt** [comment]
@flynnamy "networks" is a public available module (https://pypi.org/project/networks/), so having it in the requirements.txt seams correct for me. Another thing is the "net" module, which seems proprietary to the team and required to get the NCE loss working.

Disclaimer: I am not connected to the Diffstyler team, just tried out the repo myself and share my experience.

**Comment by zhangquanwei962** [comment]
> @flynnamy "networks" is a public available module (https://pypi.org/project/networks/), so having it in the requirements.txt seams correct for me. Another thing is the "net" module, which seems proprietary to the team and required to get the NCE loss working.
> 
> Disclaimer: I am not connected to the Diffstyler team, just tried out the repo myself and share my experience.

Hi, you can see more information from https://github.com/JunlinHan/DCLGAN/blob/main/models/networks.py and https://github.com/zyxElsa/CAST_pytorch/blob/main/models/net.py

**Comment by Lcgcl** [comment]
Using device: cuda:0
Traceback (most recent call last):
  File "main.py", line 474, in <module>
    main()
  File "main.py", line 209, in main
    netF = networks.define_F(args.input_nc, 'mlp_sample', args.normG,
  File "/home/lcg/PycharmProjects/Diffusion/Diffstyler/networks.py", line 274, in define_F
    net = PatchSampleF(use_mlp=True, init_type=init_type, init_gain=init_gain, gpu_ids=gpu_ids, nc=opt.netF_nc)
AttributeError: 'NoneType' object has no attribute 'netF_nc'

I added two python files to it and the framework still doesn't work

**Comment by Lcgcl** [comment]
> > @flynnamy "networks" is a public available module (https://pypi.org/project/networks/), so having it in the requirements.txt seams correct for me. Another thing is the "net" module, which seems proprietary to the team and required to get the NCE loss working.
> > Disclaimer: I am not connected to the Diffstyler team, just tried out the repo myself and share my experience.
> 
> Hi, you can see more information from https://github.com/JunlinHan/DCLGAN/blob/main/models/networks.py and https://github.com/zyxElsa/CAST_pytorch/blob/main/models/net.py

I added two python files to it and the framework still doesn't work

**Comment by Lcgcl** [comment]
Traceback (most recent call last):
  File "main.py", line 474, in <module>
    main()
  File "main.py", line 468, in main
    run()
  File "main.py", line 459, in run
    out = sampling.iplms_sample(cfg_model_fn, x, steps.flip(0)[:-1], {})
  File "/home/lcg/miniconda3/envs/diffstyler/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lcg/PycharmProjects/Diffusion/Diffstyler/diffusion/sampling.py", line 308, in iplms_sample
    x, eps, pred = iplms_step(model_fn, x, old_eps, steps[i] * ts, steps[i + 1] * ts, extra_args)
  File "/home/lcg/PycharmProjects/Diffusion/Diffstyler/diffusion/sampling.py", line 284, in iplms_step
    eps = eps_model_fn(x, t_1, **extra_args)
  File "/home/lcg/PycharmProjects/Diffusion/Diffstyler/diffusion/sampling.py", line 145, in eps_model_fn
    v = model(x, t, **extra_args)
  File "/home/lcg/PycharmProjects/Diffusion/Diffstyler/diffusion/sampling.py", line 154, in autocast_model_fn
    return model(*args, **kwargs).float()
  File "main.py", line 429, in cfg_model_fn
    v1 = cond_model_fn(x, t)
  File "main.py", line 312, in cond_model_fn
    cond_grad = cond_fn(x, t, pred, **extra_args).detach()
  File "main.py", line 388, in cond_fn
    loss_NCE =calculate_NCE_loss(init.detach().to(device), pred.detach().to(device))
  File "main.py", line 325, in calculate_NCE_loss
    feat_k_pool, sample_ids = netF(feat_k, args.num_patches, None)
  File "/home/lcg/miniconda3/envs/diffstyler/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lcg/PycharmProjects/Diffusion/Diffstyler/networks.py", line 588, in forward
    x_sample = mlp(x_sample)
  File "/home/lcg/miniconda3/envs/diffstyler/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lcg/miniconda3/envs/diffstyler/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/lcg/miniconda3/envs/diffstyler/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lcg/miniconda3/envs/diffstyler/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x512 and 32x256)

**Comment by Jaredddddd** [comment]
> > @flynnamy "networks" is a public available module (https://pypi.org/project/networks/), so having it in the requirements.txt seams correct for me. Another thing is the "net" module, which seems proprietary to the team and required to get the NCE loss working.
> > Disclaimer: I am not connected to the Diffstyler team, just tried out the repo myself and share my experience.
> 
> Hi, you can see more information from https://github.com/JunlinHan/DCLGAN/blob/main/models/networks.py and https://github.com/zyxElsa/CAST_pytorch/blob/main/models/net.py

好像还是跑不通代码呀

**Comment by haha-lisa** [comment]
Sorry about that. Files have been added.

**Comment by Mactor2018** [comment]
> Sorry about that. Files have been added.

Thanks for your excellent work and help. However, I still encounter a problem possibly related to this issue:
```ImportError: cannot import name 'danbooru_128' from partially initialized module 'diffusion.models' (most likely due to a circular import) (/path/to/project/Diffstyler/diffusion/models/__init__.py)```

The Python file `models.py` in the directory `Diffstyler/diffusion/models` tries to import "cc12m_1, danbooru_128, imagenet_128, wikiart_128, wikiart_256, yfcc_1, yfcc_2", but only "cc12m_1.py" and "wikiart_256.py" exist. I found some cache files related to the missing ones in the directory `Diffstyler/diffusion/models/__pycache__/`.

I saw you uploaded two files named `net.py` and `networks.py` on Nov 14, 2023. Could you please tell me how to edit the code in `main.py` so that it can run?

**Comment by Mactor2018** [comment]
> > > @flynnamy "networks" is a public available module (https://pypi.org/project/networks/), so having it in the requirements.txt seams correct for me. Another thing is the "net" module, which seems proprietary to the team and required to get the NCE loss working.
> > > Disclaimer: I am not connected to the Diffstyler team, just tried out the repo myself and share my experience.
> > 
> > 
> > Hi, you can see more information from https://github.com/JunlinHan/DCLGAN/blob/main/models/networks.py and https://github.com/zyxElsa/CAST_pytorch/blob/main/models/net.py
> 
> 好像还是跑不通代码呀

请问您能跑通代码了吗？

**Comment by haha-lisa** [comment]
I only used "cc12m_1.py" and "wikiart_256.py" in this work, and you can delete the extra model imported.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "haha-lisa/Diffstyler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月26日(星期五) 晚上6:36
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [haha-lisa/Diffstyler] missing files (Issue #2)





  
Sorry about that. Files have been added.
  
Thanks for your excellent work and help. However, I still encounter a problem possibly related to this issue:
 ImportError: cannot import name 'danbooru_128' from partially initialized module 'diffusion.models' (most likely due to a circular import) (/path/to/project/Diffstyler/diffusion/models/__init__.py)
 
The Python file models.py in the directory Diffstyler/diffusion/models tries to import "cc12m_1, danbooru_128, imagenet_128, wikiart_128, wikiart_256, yfcc_1, yfcc_2", but only "cc12m_1.py" and "wikiart_256.py" exist. I found some cache files related to the missing ones in the directory Diffstyler/diffusion/models/__pycache__/.
 
I saw you uploaded two files named net.py and networks.py on Nov 14, 2023. Could you please tell me how to edit the code in main.py so that it can run?
